### PR TITLE
Escape LIKE wildcards on every adapter and emit an ESCAPE clause

### LINKED ISSUE #1581: LIKE predicates do not escape values in SQLite and other non-MySQL/PostgreSQL RDBMS
**Summary**

Ransack's `*_cont`, `*_not_cont`, and similar LIKE-based predicates correctly escape special characters in MySQL, PostgreSQL, and PostGIS. However, in SQLite and other RDBMS, escaping is skipped, which can lead to unintended matches when values contain `%` or `_`.

**Steps to Reproduce**

Run a Ransack query using `*_cont: '%_'` against a dataset that includes values with and without underscores. In SQLite, the query matches records that do not contain underscores, due to lack of escaping.

**Expected Behavior**

The query should escape `%` and `_` so that they are treated as literal characters in all supported databases.

**Actual Behavior**

In SQLite, the escaping is skipped, resulting in unintended matches.

**Environment**

- Ruby: 3.4.5  
- Rails: 8.0.2  
- Ransack: commit 90a602a992f4e3a438d63e0fc2f7e1a0fb3acab0  
- sqlite3-ruby: 2.7.3

**Code Reference**

`escape_wildcards` skips escaping for non-MySQL/PostgreSQL adapters. https://github.com/activerecord-hackery/ransack/blob/90a602a992f4e3a438d63e0fc2f7e1a0fb3acab0/lib/ransack/constants.rb#L162-L174

**Test Reference**

`predicate_spec.rb` asserts that escaping is not applied in SQLite. https://github.com/activerecord-hackery/ransack/blob/90a602a992f4e3a438d63e0fc2f7e1a0fb3acab0/spec/ransack/predicate_spec.rb#L158-L176

**Suggested Fix**

Use `ActiveRecord::Base.sanitize_sql_like` to escape LIKE values consistently across all adapters.
https://api.rubyonrails.org/v8.0.2/classes/ActiveRecord/Sanitization/ClassMethods.html#method-i-sanitize_sql_like

**Reproduction Code**

```ruby
# frozen_string_literal: true

# Create Gemfile dynamically
File.write('Gemfile', <<~GEMFILE)
  source 'https://rubygems.org'
  gem 'rails', '8.0.2'
  gem 'ransack', github: 'activerecord-hackery/ransack', ref: '90a602a992f4e3a438d63e0fc2f7e1a0fb3acab0'
  gem 'sqlite3', '2.7.3'
GEMFILE

# Install dependencies
system 'bundle install'

# Setup Bundler
require 'bundler'
Bundler.setup(:default)

# Require necessary libraries
require 'active_record'
require 'logger'
require 'ransack'

# Setup in-memory SQLite DB
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new($stdout)

# Define schema
ActiveRecord::Schema.define do
  create_table :products, force: true do |t|
    t.string :name
  end
end

# Define model
class Product < ActiveRecord::Base
  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end
end

# Seed data
Product.create!(name: '100% Pure')
Product.create!(name: '50_50 Blend')
Product.create!(name: 'Back\\Slash')
Product.create!(name: 'NormalText')

# Ransack query with special characters
q = Product.ransack(name_cont: '%_')
puts "\nGenerated SQL:"
puts q.result.to_sql
puts "\nResults:"
puts q.result.map(&:name)
```

**Output (Excerpt)**

```
Generated SQL:
SELECT "products".* FROM "products" WHERE "products"."name" LIKE '%%_%'

Results:
100% Pure
50_50 Blend
Back\Slash
NormalText
```

### PR DESCRIPTION
**Pull request by scarroll32**
> [!NOTE]
> This PR was opened by **Claude** (Claude Code), acting on behalf of @scarroll32.
> It builds on @heyjosephme's #1660 — thank you for the report and the starting point.

Fixes #1581. Supersedes #1660.

## The bug

`Constants.escape_wildcards` only escaped `%`, `_` and `\` on MySQL, PostgreSQL and PostGIS. Every other adapter fell through to `else: unescaped`, so a wildcard typed by a user was passed straight into the `LIKE` pattern:

```ruby
# SQLite, before
Person.create!(name: 'a_c')
Person.create!(name: 'abc')
Person.ransack(name_cont: 'a_c').result.count  # => 2   ← 'abc' should not match
```

This is a silent wrong-results bug, and it applies to any search field a user can type into.

## Why escaping alone isn't the fix

#1660 proposed replacing the adapter switch with `sanitize_sql_like`, which escapes on all adapters. That's the right first half, but it fails four existing specs, and those failures are real rather than cosmetic:

**MySQL and PostgreSQL treat `\` as the default `LIKE` escape character. SQLite has no default at all.** On SQLite a backslash in a pattern is just a backslash, so escaping without an `ESCAPE` clause turns `a_c` into the pattern `a\_c`, which now matches neither `a_c` nor `abc`. The bug changes shape instead of going away.

## The fix

Two halves:

1. **`escape_wildcards` escapes unconditionally** — no adapter check.
2. **`Condition#format_predicate` passes the escape character to Arel**, so every `LIKE` / `NOT LIKE` carries `ESCAPE '\'`. Arel's `matches`, `matches_any`, `matches_all` and the `does_not_match` trio all accept it as their second argument.

```sql
-- after
SELECT "people".* FROM "people" WHERE "people"."name" LIKE '%a\_c%' ESCAPE '\'
```

Behaviour is now identical on every backend and no longer depends on the default escape character.

## Incidental improvements

- **`.` is no longer escaped on PostgreSQL.** It isn't a `LIKE` wildcard; `\.` and `.` match the same thing, so this only ever produced noisier SQL.
- **The adapter check is gone**, which removes a call to the deprecated `ActiveRecord::Base.connection` from the value-formatting path — one fewer private/deprecated Active Record touchpoint, per the direction discussed in #1640.
- **`like_predicate?` now recognises the `_any` / `_all` compound forms** (`matches_any`, `does_not_match_all`, …). They take the same escape argument and were previously missed, so `name_cont_any` would have kept the old broken behaviour even after the fix.

## Tests

Two new regression specs in `base_spec.rb` that assert on **results, not SQL** — they fail on `main` and pass here:

- `treats an underscore in the search term literally` — `a_c` must not match `abc`
- `treats a percent sign in the search term literally` — `dis%count` must not match `discount`

The existing per-adapter wildcard expectations were four blocks of escaped-regex-inside-escaped-regex. Since escaping no longer varies by adapter, they now compute the expected literal via a new `quote_value` spec helper (`connection.quote`) and only branch on the operator (`LIKE` vs `ILIKE`, `LOWER()` wrapping). Considerably easier to read, and correct on every backend by construction.

Full suite: **530 examples, 0 failures, 1 pending** (Rails 8.1.3 / Ruby 3.4.9 / SQLite).

## Docs

Adds a "Wildcards in `LIKE` predicates" section to the Search Matchers page explaining that `cont`/`start`/`end` take literal text while `matches` takes a pattern, and updates the `*_present` / `*_blank` rows for the non-string-column behaviour introduced in #1678.

## Compatibility

Breaking for anyone who was relying on the old SQLite behaviour to smuggle a wildcard through `cont` — that path was never documented and produced adapter-dependent results. `matches` remains the supported way to pass a pattern. Appropriate for 5.0.0 (#1640).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: lib/ransack/nodes/condition.rb [hunk 1]
```diff
@@ -357,13 +357,19 @@ def format_predicate(attribute)
...
+        # actually honoured. Without an explicit ESCAPE clause, SQLite treats a
+        # backslash as a literal character rather than an escape.
+        # See https://github.com/activerecord-hackery/ransack/issues/1581
         if like_predicate?(arel_pred)
           arel_values = Arel::Nodes.build_quoted(arel_values)
+          predicate = attr_value_for_attribute(attribute)
+                      .public_send(arel_pred, arel_values, Constants::LIKE_ESCAPE_CHARACTER)
+        else
+          predicate = attr_value_for_attribute(attribute).public_send(arel_pred, arel_values)
         end
```
[the remark this answers is not in the document]
Comment (scarroll32) [reply lib/ransack/nodes/condition.rb:383]: > [!NOTE]
> Reply from **Claude** (Claude Code), acting on behalf of @scarroll32.

You were right, and it was worse than incorrect SQL — it was a crash I introduced. Every compound LIKE predicate raised `NoMethodError: undefined method 'map' for an instance of Arel::Nodes::Quoted`, because widening `like_predicate?` sent the whole Array through `build_quoted` as one node. The suite had no spec for any `_any`/`_all` LIKE form, which is why it was green.

Fixed in 68ff77cd: elements are quoted individually when `arel_values` is an Array. Four result-based specs added (`cont_any`, `cont_all`, `not_cont_any`, `start_any`), including that each expanded LIKE carries its own `ESCAPE` clause.

[the remark this answers is not in the document]
Comment (scarroll32) [reply lib/ransack/nodes/condition.rb:383]: > [!NOTE]
> Reply from **Claude** (Claude Code), acting on behalf of @scarroll32.

Follow-up: the specs in 68ff77cd were themselves wrong (rows persist across examples in that file, and I had the `not_cont_any` semantics backwards — it is `NOT LIKE a OR NOT LIKE b`). Corrected in 890323dc; the fix in `format_predicate` is unchanged and the full suite is green.
