### PR TITLE
Make ransack work with Rails 7.2

### LINKED ISSUE #1491: Getting with_connection for an instance of ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
I am using edge rails and it fails with this rails [commit()](https://github.com/rails/rails/commit/fa048105d145536538b923fa57465bdeee559e88)

i am getting this error when i use ransack queries. When i use AR queries, the error does not happen.

```
NoMethodError (undefined method `with_connection' for an instance of ActiveRecord::ConnectionAdapters::PostgreSQLAdapter):
  
rails (d7980c6b1091) activerecord/lib/active_record/associations/alias_tracker.rb:10:in `create'
ransack (4.1.1) lib/ransack/adapters/active_record/context.rb:281:in `build_joins'
ransack (4.1.1) lib/ransack/adapters/active_record/context.rb:249:in `join_dependency'
ransack (4.1.1) lib/ransack/context.rb:40:in `initialize'
ransack (4.1.1) lib/ransack/context.rb:13:in `new'
ransack (4.1.1) lib/ransack/context.rb:13:in `for_class'
ransack (4.1.1) lib/ransack/context.rb:27:in `for'
ransack (4.1.1) lib/ransack/search.rb:32:in `initialize'
ransack (4.1.1) lib/ransack/adapters/active_record/base.rb:16:in `new'
ransack (4.1.1) lib/ransack/adapters/active_record/base.rb:16:in `ransack'
activeadmin (3.2.1) lib/active_admin/resource_controller/data_access.rb:218:in `apply_filtering'
activeadmin (3.2.1) lib/active_admin/resource_controller/data_access.rb:60:in `block in find_collection'
activeadmin (3.2.1) lib/active_admin/resource_controller/data_access.rb:59:in `each'
activeadmin (3.2.1) lib/active_admin/resource_controller/data_access.rb:59:in `find_collection'
activeadmin (3.2.1) lib/active_admin/resource_controller/data_access.rb:45:in `collection'
inherited_resources (1.14.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (3.2.1) lib/active_admin/resource_controller/streaming.rb:13:in `index'
rails (d7980c6b1091) actionpack/lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
rails (d7980c6b1091) actionpack/lib/abstract_controller/base.rb:226:in `process_action'
rails (d7980c6b1091) actionpack/lib/action_controller/metal/rendering.rb:193:in `process_action'
rails (d7980c6b1091) actionpack/lib/abstract_controller/callbacks.rb:261:in `block in process_action'
rails (d7980c6b1091) activesupport/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
rails (d7980c6b1091) actiontext/lib/action_text/rendering.rb:25:in `with_renderer'
rails (d7980c6b1091) actiontext/lib/action_text/engine.rb:71:in `block (4 levels) in <class:Engine>'
rails (d7980c6b1091) activesupport/lib/active_support/callbacks.rb:130:in `instance_exec'
rails (d7980c6b1091) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'

### PR DESCRIPTION
**Pull request by gregmolnar**
…urselves.  Closes #1491.

### CODE REVIEW

**Comment by gregmolnar** [comment]
This one closes #1489 too.

**Comment by night91** [comment]
This PR added a breaking change, if you use Rails 7.1 you will get this error, when you were supporting rails 7.2.
I need now to roll back to ransack 4.1 till probably Rails 7.2 is fully released.

**Comment by gregmolnar** [comment]
@night91 can you show me the error you are getting? The test suite is passing with 7.1.0, is that the version you are on?

**Comment by louiswdavis** [comment]
Also having the problem with Rails 7.1.3.4 & Ransack 4.2.0. Rolling back Ransack hasn't managed to help us though.

**The Error**
```
NoMethodError (undefined method `with_connection' for Rating:Class
Did you mean?  with_options):
  
app/controllers/concerns/programmes.rb:28:in `search_and_sort_applications'
app/controllers/programmes_controller.rb:75:in `show'
app/controllers/application_controller.rb:237:in `set_time_zone'
Started GET "/serviceworker.js" for ::1 at 2024-08-05 13:25:56 +0100
  
ActionController::RoutingError (No route matches [GET] "/serviceworker.js"):
```

**Params**
```
{ "q"=> { "ratings_account_id_not_in"=>["1"] } }
```

**Models**
```
class Application < ApplicationRecord
  belongs_to :added_by, class_name: 'Account'
  has_many :ratings, dependent: :destroy
  # ...
end

class Rating < ApplicationRecord
  belongs_to :account, optional: true
  belongs_to :application
  # ...
end
```

**Comment by Carmer** [comment]
rails 7.1.3.4
ransack: 4.20

Same error as above

```
NoMethodError (undefined method `with_connection' for ModelName:Class
Did you mean?  with_options):
```

**Comment by gregmolnar** [comment]
My version comparison is incorrect. I will fix it a little later today and cut a new release. Thanks for reporting!
