### ISSUE TITLE
searchable_attributes not working after ransack update to 2.4.0

### ISSUE THREAD

**Issue by amolbudkhe** [activerecord-hackery/ransack#1356]
After updating the Rails version to 6.1 we were facing **undefined method `construct_tables!`** to solve this issue we upgraded the Ransack to `2.4.0`.

After upgrading the Ransack, Our advance search is not working correctly. Advance search attributes that were added in the `searchable_attributes` method are not appearing and the default attributes i.e. DB column name are showing.

Before upgrading the Ransack to`2.4.0` everything was working seamlessly.

**Comment by scarroll32** [comment]
@amolbudkhe could you please provide some sample code that causes this issue, or even better, submit a PR with a failing test? 

Thanks! 🙏

**Comment by amolbudkhe** [comment]
Hi @scarroll32,

We don't have Test cases written for this scenario, But I'll add the code snippets.

Model.rb

```
def self.searchable_attributes
    [{ name: :current_profile_version_name, type: :string, label: 'Profile Name' },
     { name: :current_profile_version_description, type: :string, label: 'Description' },
     { name: 'created_at', type: :date, label: 'Date Created' },
     { name: 'updated_at', type: :date, label: 'Date Modified' },
     { name: :last_modified_by_username, type: :string, label: 'Last Modified By' }]
  end
```

initializers/ransacker.rb
```
module Ransack
  module Helpers
    class FormBuilder < (ENV['RANSACK_FORM_BUILDER']&.constantize ||
        ActionView::Helpers::FormBuilder)

      def searchable_collections
        collections = Hash.new
        object.context.klass.searchable_attributes.each do |attr|
          if attr[:type] == :collection
            collection = attr[:collection]
            value_method = attr[:value_method] ? attr[:value_method] : :to_s
            text_method = attr[:text_method] ? attr[:text_method] : :to_s
            collections.merge!(attr[:name] => {collection: collection, value_method: value_method, text_method: text_method})
          end
        end
        collections
      end

      def searchable_predicates
        predicates = Hash.new
        object.context.klass.searchable_attributes.each do |attr|
          if attr[:predicates]
            predicates.merge!(attr[:name] => attr[:predicates])
          end
        end
        predicates
      end

      def template_collection_select(name, collection, options, html_options)
        if options[:custom_attributes]
          @template.select(@object_name, name,
            object.context.klass.searchable_attributes.map do |c|
              data_attrs = { type: c[:type] }
              data_attrs[:predicate] = c[:predicate] if c[:predicate]
              [c[:label], c[:name], { data: data_attrs }]
            end,
            objectify_options(options),
            @default_options.merge(html_options))
        else
          @template.collection_select(
            @object_name, name, collection, :first, :last,
            objectify_options(options), @default_options.merge(html_options)
          )
        end
      end
    end
  end
end

Ransack.configure do |config|
  config.custom_arrows = {
    up_arrow: '<i class="icon-sort-up"></i>',
    down_arrow: '<i class="icon-sort-down"></i>',
    default_arrow: '<i class="default-arrow-icon"></i>'
  }

  config.add_predicate('before',
                       arel_predicate: 'lt',
                       formatter: proc { |v| v.to_date },
                       validator: proc { |v| v.present? },
                       compounds: false,
                       type: :string)

  config.add_predicate('after',
                       arel_predicate: 'gt',
                       formatter: proc { |v| v.to_date },
                       validator: proc { |v| v.present? },
                       compounds: false,
                       type: :date)

  config.add_predicate('date_eq',
                       arel_predicate: 'between',
                       formatter: proc { |v| OpenStruct.new(begin: "#{v.to_date}%", end: "#{v.to_date} 23:59:59")},
                       validator: proc { |v| v.present? },
                       compounds: false,
                       type: :date)
  config.sanitize_custom_scope_booleans = false
end
```

condition field partial
```
.query-predicate.js-fields-search
  .attribute
    = f.attribute_fields do |a|
      div data-object-name="#{f.object_name}"
        = a.attribute_select({ include_blank: false, custom_attributes: true }, { class: 'js-search-attributes' })
  .selector
    div
      = f.predicate_select({ only: [:cont, :not_cont, :start, :end, :eq], compounds: false }, { class: 'js-search-string' })
      = f.predicate_select({ only: [:before, :after, :date_eq], compounds: false }, { class: 'js-search-date' })
      = f.predicate_select({ only: [:lt, :eq, :gt], compounds: false }, { class: 'js-search-number' })
      = f.predicate_select({ only: [:eq, :not_eq], compounds: false }, { class: 'js-search-collection' })
      = f.predicate_select({ only: [:in], compounds: false }, { class: 'js-search-in-collection' })
      - f.searchable_predicates.each do |name, predicates|
        = f.predicate_select({ only: predicates, compounds: false }, { class: "js-search-#{name}" })
  .value
    = f.value_fields do |v|
      div data-object-name="#{v.object_name}"
      = render 'value_fields', v: v, f: f
  .controls
    button.btn.btn-xs.btn-default.js-remove-fields-search -
```

I added logger in the ransacker.rb in the `template_collection_select` method and found that the `template_collection_select` method is not getting called after the ransack update. In the older version of ransack `template_collection_select` method is getting called. After Ransack update this method is not getting called.
