### ISSUE TITLE
Searching for multiple attributes in belongs_to raises undefined method error

### ISSUE THREAD

**Issue by D4uS1** [activerecord-hackery/ransack#1428]
Hey all,

if i use a search field targeting multiple fields in a belongs_to association (like described in [the documentation](https://activerecord-hackery.github.io/ransack/going-further/associations/)) i will get an "undefined method" error for "Ransack::Search<class: Customer, base: Grouping <combinator: and>>:Ransack::Search".

Suppose you have the following models:
```
class Customer < ApplicationRecord
  belongs_to :address, optional: true
end

class Address < ApplicationRecord
  has_many :customers, dependent: :nullify

  # this model has the attributes street_and_number, city, zip_code and country
end
```

Now if i submit the following search form:
```
<%= search_form_for @q do |f| %>
  <%= f.label 'Address' %>
  <%= f.search_field :address_city_or_address_zip_code_or_address_country_cont %>

  <%= f.submit "search" %>
<% end %>
```

I will get the following error:
```
undefined method `address_city_or_address_zip_code_or_address_country_cont' for Ransack::Search<class: Customer, base: Grouping <combinator: and>>:Ransack::Search
```

This seems to be only an issue for belongs_to associations. For has_many associations, this works fine. (For sure by using "addresses" instead of "address").

Thank you for help :)

**Comment by ronualdo** [comment]
I'm having the same problem here. I can provide a working example if that helps.

**Comment by scarroll32** [comment]
> [!NOTE]
> Comment from **Claude** (Claude Code), acting on behalf of @scarroll32.

Multi-attribute `_or_` conditions on a `belongs_to` work on 5.0.0. The `undefined method ... for Ransack::Search` message is what the form builder raises when the condition was silently dropped, which happens when `address` is missing from `Customer.ransackable_associations` or `Address` has no `ransackable_attributes` (both are mandatory since 4.0). Set `config.ignore_unknown_conditions = false` to get the real reason. Closing; please reopen with a runnable script if it still fails after allowlisting.
