### ISSUE TITLE
1.6.0 Regression: Searching with array arguments.

### ISSUE THREAD

**Issue by keichan34** [activerecord-hackery/ransack#492]
Works in 1.5.1:

```ruby
> User.ransack(id_in: [1, 2]).result.to_sql
=> "SELECT `users`.* FROM `users` WHERE `users`.`id` IN (1, 2)"
```

1.6.0:

```ruby
> User.ransack(id_in: [1, 2]).result.to_sql
NoMethodError: undefined method `map' for 1:Fixnum
from /___/.gem/ruby/2.2.0/gems/ransack-1.6.0/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:34:in `return_predicate'
```

https://github.com/activerecord-hackery/ransack/blob/v1.6.0/lib/ransack/adapters/active_record/ransack/nodes/condition.rb#L34

Tested on the current master (9d56e60f98355322b9e7774b084c345ac942e34b), same results.

Seems to be related to the fix in #472.

Is this just me, or are other people having problems with this too?

**Comment by jonatack** [comment]
Thanks. Issue reported by #493 and I've reproduced it as well.

**Comment by jonatack** [comment]
Yes, it's coming from the `map` added in #488.

**Comment by jonatack** [comment]
Pushing a fix in five minutes.

**Comment by keichan34** [comment]
Thanks for the quick fix! :+1:
